export const INCREMENTBYONE = "INCREMENTBYONE";
export const INCREMENTBYFIFTEEN = "INCREMENTBYFIFTEEN";
export const DECREMENTBYONE = "DECREMENTBYONE";
export const DECREMENTBYTEN = "DECREMENTBYFIFTEEN";
